### ISSUE TITLE
Udk with express server for e2e

### ISSUE THREAD

**Issue by thedewpoint** [enten/angular-universal#15]
Quick question. I see that during the dev task the node server as well as the angular client are created and started successfully. My angular app depends on some server parameters related to x-forwarded-host headers. Because of this I need my express server running during e2e mode so that my app can get those params. Is there any straightforward way to do this using udk?

**Comment by enten** [comment]
@thedewpoint  

I will try to summarize your need, please correct me if i'm wrong.

When your run your application are delivered by your server bundle: browser bundle served works because some server side instructions are executed (like configure http headers).

But in your e2e environement: your browser bundle tests failed due to server bundle stuff which aren't executed.

**Is that summary right?**

Your issue sound like others environment's side-effect testing issues.

I think we can solve your issue by mock partially (by using server bundle) or fully (by using only mock instances) server side stuff.

**Comment by thedewpoint** [comment]
@enten yes I think you have it. My angular app is dependent on my express server to load up some configurations based on request headers. Because of this my e2e tests need my node server to be running. I'm wondering how to do this using your library so that way i can get live reload while testing

**Comment by enten** [comment]
Unfortunately, udk doesn't provide builder or dev container to answer your need.

You need to write a custom architect builder based on the [ProtractorBuilder](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/protractor/index.ts).

It would be a wonderful dev experience if we bring universal hmr into e2e testing environement.
It's a good idea. For the moment, I can't develop your idea (and others like nestjs integration, better i18n integration, ...). May be for the next year.
