### ISSUE TITLE
Build Out of Memory Problem

### ISSUE THREAD

**Issue by Ascone82** [enten/angular-universal#16]
`"C:\Program Files\JetBrains\WebStorm 2018.2.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start-local --scripts-prepend-node-path=auto

> speffy@4.0.0 prestart-local C:\Users\vince\Projects\speffyuniversalmaterialv3
> npm run build:local

> speffy@4.0.0 build:local C:\Users\vince\Projects\speffyuniversalmaterialv3
> ng run ng-universal:udk:local

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArray
 5: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey
 6: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::AtPut
 7: v8::internal::compiler::RawMachineAssembler::MakeNode
 8: 00000183BF2843C1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! speffy@4.0.0 build:local: `ng run ng-universal:udk:local`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the speffy@4.0.0 build:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vince\AppData\Roaming\npm-cache\_logs\2018-09-04T12_01_19_169Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! speffy@4.0.0 prestart-local: `npm run build:local`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the speffy@4.0.0 prestart-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vince\AppData\Roaming\npm-cache\_logs\2018-09-04T12_01_19_196Z-debug.log

Process finished with exit code 3
`

What's wrong?!?!

**Comment by enten** [comment]
@Ascone82
It's an out of memory issue.

I don't know the cause of that out of memory issue.
But I don't think that udk is the source of that issue because udk through udk-builder delegates the works to angular-cli and webpack.

It would be rather related to your runtime environment (platform and v8 engine).

Have you tried to adjust v8 memory options like `--stack-size`, `--max_new_space_size` or `--max_old_space_size`?

May it's your code which have memory leak? May it's you os which restrict v8 memory?
There may be many sources.

Can you try to run your code on a linux environment (with enough memory space of course)?
