### ISSUE TITLE
Dynamic content on click button

### ISSUE THREAD

**Issue by mighty-nyaina** [enten/angular-universal#21]
Hi!
Is it possible to get for example a list of elements using http request, but not in ngOnInit but on click of a button for example, and get the list when seeing page source in the browser?

Thanks

**Comment by enten** [comment]
@mighty-nyaina My apologies for the late answer.

Firstly, fetch remote data after an event was triggered (like click on a button) rather than triggered it in `ngOnInit` is easy to achieve with [HttpClient](https://angular.io/api/common/http/HttpClient).

But about "get the list when seeing page source in the browser": I think there is some misinterpretations.

If you want to seeing the example list in the page source sent by the server: you must run the request (triggered by a click) on the server.

_What do you try to achieve? What is your usecase?_
