### ISSUE TITLE
Add app-shell integration example

### ISSUE THREAD

**Issue by ghost** [enten/angular-universal#24]
App-shell improves statistics on the first contentfull point in the lighthouse benchmark

There is no clear way how to combine udk-builder and app-shell builder

**Comment by enten** [comment]
The [`udk-builder`](https://github.com/enten/udk/tree/master/angular#udkudk-builder) was created to apply [universal technique](https://angular.io/guide/universal) in a more convenient way.

`udk-builder` wasn't designed to be combined with the [`app-shell-builder`](https://github.com/angular/angular-cli/wiki/stories-app-shell).

**I think that it's possible. Which way would you like to combine the both builders?**

I don't find relations between them because it's not for the same purposes:
* I'm using the universal technique to add features on the server side like caching some pages rendered dynamically ;
* I'm using the prerender technique with the app-shell to build a progress web app which will be served as static files only.

The choice between universal and prerender technique depends on your needs.

But we are still able to configure the app-shell-builder (in the `angular.json`) and make it works with the server and browser targets. For example: we can add a new configuration named "app-shell" in browser and server targets and reference them in the `app-shell` target as below.

```json
"app-shell": {
  "builder": "@angular-devkit/build-angular:app-shell",
  "options": {
    "browserTarget": "my-app:build:app-shell",
    "serverTarget": "my-app:server:app-shell",
    "route": "shell"
  }
}
```

Finally, we can serve prerendered pages easily by using [express.static](https://expressjs.com/en/4x/api.html#express.static) on the server side.

Please note that the previous way described to combine the both builders is the simplest.

**The tricky point that I see is the use of the [PWA technique](https://angular.io/guide/service-worker-intro) to improve performances on browser side.** We previously worked on [service worker support with the udk-builder](https://github.com/enten/angular-universal/issues/14#issuecomment-414128275) (with `@angular/cli@6.2.0-beta.2`) but I don't know if that still works. 

**We can write an example to combine the both builders but I need to understand how you want to achieve that.**
