### ISSUE TITLE
changes are not reflected in server build

### ISSUE THREAD

**Issue by eyalhakim** [enten/angular-universal#35]
Any changes are not being reflected in server build until I kill the process and rerun `npm run dev`.

**Comment by enten** [comment]
Can you provide more information to investigate your issue:
* angular and udk versions
* log output
* repo which reproduce your issue.

Thanks.

**Comment by wundo** [comment]
@enten I'm experiencing something very similar, but the opposite.

My SSR renders perfect, but after the frontend bootstraps its reverts back to a previous version of the code, I can tell this because I manually added some text to the templates that should up when the page first loads, and disappears when the frontend bootstrap.

**Comment by enten** [comment]
@wundo 
May there is a problem with the hot middleware which is inject on the server.

To make hot middleware works well the [server entry point](https://github.com/enten/angular-universal/blob/master/src/server.ts) must export the server instance.

Do you have a repo which reproduce the issue?
