### ISSUE TITLE
Does this project offer HMR and SSR simultaneously?

### ISSUE THREAD

**Issue by laurencefass** [enten/angular-universal#43]
The development cycle using default SSR universal functionality is so cumbersome its unusable (the way Im using it anyway).

Im having to rebuild the project for every change i make which is impossible for metatag tuning. I can't even make source code changes for manual reload with angular universal. Does this project offer HMR and SSR simultaneously?

i.e. can i make changes to a universal app and see them update in the browser?

thanks

**Comment by enten** [comment]
@laurencefass 

That boilerplate use a **specific builder ([udk:udk-builder](https://github.com/enten/udk/tree/master/angular#udkudk-builder)) which allow to build an angular application for both browser and server in same webpack compilation**.

When using the dev builder ([udk:udk-runner](https://github.com/enten/udk/tree/master/angular#udkudk-runner)), **HMR is enabled for the both browser and server sides as you can see [here](https://github.com/enten/angular-universal#development-server)**.

**Comment by laurencefass** [comment]
To confirm: browser and server HMR working for all versions Angular 8? 

I think i should be able to use this to fine tune SEO parameters with HMR/SSR? Is that correct?

thanks

**Comment by laurencefass** [comment]
Will you update this for Angular 9 and will there still be a need for it in the future now Angular 9 Universal supports live reload? I'm just testing the office dev:ssr build and its very slow and doesn't support --public-host yet so not so good with /paths and reverse proxies.  Performance doesn't compare with Razzle, Next, Nuxt etc which offer near instant page reloads. Please can you comment on the performance of this package vs Angular 9 Universal live reload.

**Comment by enten** [comment]
@laurencefass 

I can't confirm that HMR on browser/server sides works with all versions of Angular 8 (I think breaking change in devkit beginning in v8).

Currently, the master branch of this boilerplate works with angular 9.0.0-rc.6 and had works with lot of versions since angular 6.

I'm agree with you: workflows given in angular docs is too heavy (3 builds are needed in 3 different webpack compiler).

It was a pain to develop angular universal in this way. So we develop specific builders (in udk package) to optimize all the things.

As you can see [here](https://imgur.com/a/cpbhHgg): we can make HMR works on both sides.

In term of productivity during development and build: it's faster than angular universal official workflows (because angular server and browser are built in same webpack compiler and we don't need a third build for a server only).

In term of performance during runtime: it's equals because is the same sofware (express server with ng express engine). Each request trigger a server side rendering of your angular app. You can combine some routes with a middleware which cache result for example.

You can try yourself HMR on both sides:

```
git clone https://github.com/enten/angular-universal
cd angular-universal
npm install
ng serve
```

After server is running, try to update src/app/welcome/welcome.component.ts to check HMR on browser and server sides.

You can try universal build with `ng build`.
