### ISSUE TITLE
 Can't bind to 'errorImage' since it isn't a known property of 'img'.

### ISSUE THREAD

**Issue by vivek2s2** [enten/angular-universal#76]
I'm using ng-lazyload-image & followed the documentation by importing in module & using it like this 

<img [defaultImage]="'./assets/deleted_user.jpg'" [lazyLoad]="'./assets/lazy.jpg'" [errorImage]="'./assets/error.jpg'" alt="Top nav image" style="  height: 16.5px;
margin-bottom: 4px;">

but it's throwing error: 
Can't bind to 'defaultImage' since it isn't a known property of 'img'.
Can't bind to 'lazyLoad' since it isn't a known property of 'img'.
Can't bind to 'errorImage' since it isn't a known property of 'img'.

**Comment by enten** [comment]
Generally, that kind of errors is caused by missing module (the module which declares these directives).

I don't think that your issue is related to angular-universal repository.

If you have a repo which reproduce this error, you can reopen this issue, share the repo and we will discuss about your problem.
